
# Copyright (C) 2010--2016  Cesar Rodriguez <cesar.rodriguez@lipn.fr>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.


# == llvm ==
LLVMVERS=3.7
#LLVMCXXFLAGS=-I$(shell llvm-config-$(LLVMVERS) --includedir)
LLVMCXXFLAGS=$(shell llvm-config-$(LLVMVERS) --cppflags)
LLVMLDFLAGS=$(shell llvm-config-$(LLVMVERS) --ldflags)
#LLVMLIBS=$(shell llvm-config-$(LLVMVERS) --libs --system-libs)
LLVMLIBS=$(shell llvm-config-$(LLVMVERS) --libs all) -lz -lpthread -lffi -lncurses -ldl -lm

# == steroids ==
STIDCPPFLAGS=-I ../steroid/include/
STIDLDFLAGS=-L ../steroid/src/
#STIDLDLIBS=-Wl,-Bstatic -lsteroids -Wl,-Bdynamic
#STIDLDLIBS=-lsteroids

# traditional variables
DEFS=-D_POSIX_C_SOURCE=200809L -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS 
CFLAGS:=-Wall -std=c11 -O3
CXXFLAGS:=-Wall -std=c++11 -O3
CPPFLAGS:=-I src/ $(LLVMCXXFLAGS) $(STIDCPPFLAGS)
#LDFLAGS:=-dead_strip -static
LDFLAGS:=$(LLVMLDFLAGS) $(STIDLDFLAGS)
LDLIBS=$(STIDLDLIBS) $(LLVMLIBS)

# source code
SRCS:=$(wildcard src/*.c src/*.cc src/*/*.c src/*/*.cc src/*/*/*.c src/*/*/*.cc)
SRCS:=$(filter-out $(wildcard src/old/*), $(SRCS))
SRCS:=$(SRCS)

# do not remove files generated by lex or bison once you generate them
.SECONDARY: src/cna/spec_lexer.cc src/cna/spec_parser.cc

# source code containing a main() function
MSRCS:=$(wildcard src/main.cc)

# compilation targets
OBJS:=$(SRCS:.cc=.o)
OBJS:=$(OBJS:.c=.o)
MOBJS:=$(MSRCS:.cc=.o)
MOBJS:=$(MOBJS:.c=.o)
TARGETS:=$(MOBJS:.o=)

# dependency files
DEPS:=$(patsubst %.o,%.d,$(OBJS) $(MOBJS))

# define the toolchain
CROSS:=
VERS:=-3.7
#VERS:=

LD:=$(CROSS)ld$(VERS)
CC:=$(CROSS)clang$(VERS)
CXX:=$(CROSS)clang++$(VERS)
CPP:=$(CROSS)cpp$(VERS)
LEX:=flex
YACC:=bison

#dot file input
DOTS=$(wildcard dot/*.dot)
PDFS=$(DOTS:.dot=.pdf)
SVGS=$(DOTS:.dot=.svg)

%.d : %.c
	@echo "DEP $<"
	@set -e; $(CC) -MM -MT $*.o $(CFLAGS) $(CPPFLAGS) $< | \
	sed 's,\($*\)\.o[ :]*,\1.o \1.i $@ : ,g' > $@;

%.d : %.cc
	@echo "DEP $<"
	@set -e; $(CXX) -MM -MT $*.o $(CXXFLAGS) $(CPPFLAGS) $< | \
	sed 's,\($*\)\.o[ :]*,\1.o \1.i $@ : ,g' > $@;

%.cc : %.l
	@echo "LEX $<"
	@$(LEX) -o $@ $^

%.cc : %.y
	@echo "YAC $<"
	@$(YACC) -o $@ $^

# cancelling gnu make builtin rules for lex/yacc to c
# http://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_10.html#SEC104
%.c : %.l
%.c : %.y

%.o : %.c
	@echo "CC  $<"
	@$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

%.o : %.cc
	@echo "CXX $<"
	@$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c -o $@ $<

%.i : %.c
	@echo "CC  $<"
	@$(CC) $(CFLAGS) $(CPPFLAGS) -E -o $@ $<

%.i : %.cc
	@echo "CXX $<"
	@$(CXX) $(CXXFLAGS) $(CPPFLAGS) -E -o $@ $<

%.pdf : %.dot
	@echo "DOT $<"
	@dot -T pdf < $< > $@

%.png : %.dot
	@echo "DOT $<"
	@dot -Tpng < $< > $@

%.svg : %.dot
	@echo "DOT $<"
	@dot -Tsvg < $< > $@

CFLAGS_:=-Wall -Wextra -std=c11 -O3
CXXFLAGS_:=-Wall -Wextra -std=c++11 -O3

%.ll : %.c
	$(CC) $(CFLAGS_) -S -flto $< -o $@
%.bc : %.c
	$(CC) $(CFLAGS_) -c -flto $< -o $@
%.ll : %.cc
	$(CXX) $(CXXFLAGS_) -S -flto $< -o $@
%.bc : %.cc
	$(CXX) $(CXXFLAGS_) -c -flto $< -o $@
%.bc : %.ll
	llvm-as-$(LLVMVERS) $< -o $@
%.ll : %.bc
	llvm-dis-$(LLVMVERS) $< -o $@
%.s : %.bc
	llc-$(LLVMVERS) $< -o $@

